global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book_pipeline'
    static_configs:
      - targets: ['book_pipeline:8001']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']